### ISSUE TITLE
Startup performance

### ISSUE THREAD

**Issue by priyadarshan** [PythonNut/emacs-config#4]
Thank you for sharing your emacs-conifg, I am learning many neat things from it.

In regards to startup performance, I like the idea of not adding a dependancy to optimise loading performance, and I was wondering if you had cosidered [use-package](https://github.com/jwiegley/use-package) or other similar tools?

Thanks!

**Comment by PythonNut** [comment]
Hi @priyadarshan thanks for taking the time to ask me this.

Yes, I've definitely considered it. I usually dislike libraries that abstract what's happening behind the scenes. This is because I feel that I have lost a measure of control. Of course, there are exceptions: for example, I'd never approach cross-browser JavaScript without something like jQuery. `use-package` may very well be a package that helps more than it harms.

In general, I do some things that I haven't seen done with `use-package`.

* `icicles` requires [arbitrarily complex code](https://github.com/PythonNut/emacs-config/blob/4fa48bc9cd15d3b6770f420ac1b2b69285dcbed1/modules/config-icicles.el#L55-L64) to ensure that it doesn't drive me insane. Several other packages require non-trivial loading as well.
* I also like to defer the installation of packages (e.g. [`json-mode`](https://github.com/PythonNut/emacs-config/blob/4fa48bc9cd15d3b6770f420ac1b2b69285dcbed1/modules/config-icicles.el#L55-L64)) until they're actually needed. 
* See the [deferred `org-babel` backends] (https://github.com/PythonNut/emacs-config/blob/f17a5dffac15159e481f6b96446ba431fb676703/modules/config-modes.el#L1054-L1097) for more package-related gymnastics. 

In sum, I'm pretty happy with the system I have now, so my motivation for moving to `use-package` is not very high. In addition, I'm sure that porting to `use-package` would be a lot of work, as I would have to reimplement a lot of my current systems in terms of `use-package`'s abstractions. I haven't seen any functionality in `use-package` that I wasn't able to implement myself, AFAIK.

Of course, I could use `use-package` only for specific packages, but I believe that that defeats the purpose

**Comment by priyadarshan** [comment]
Thank you for the through and thought-provoking answer.
I share the same feeling about trying to avoid losing the touch with the underlying Emacs. It is not because of some addiction to micromanaging, it seems just against the overall "philosophy" of Emacs.
I am learning a lot from your setup.
Thank you very much!

**Comment by PythonNut** [comment]
Thanks for asking, if you have any other questions, feel free to open a new issue.
